version: '3.2'
services:
  redis-server:
    image: 'redis'
    container_name: 'ramen-ranking-redis'
    ports:
      - "6380:6379"
  macju-ranking-server:
    image: 'sangjs39/ramen-ranking-server'
    container_name: 'ramen-ranking-server'
    ports:
      - "8081:8081"
