# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: fetch-ramen-pipeline
  path.config: "/usr/share/logstash/pipeline/fetch-ramen.conf"

# - pipeline.id: fetch-nutrient-pipeline
#   path.config: "/usr/share/logstash/pipeline/fetch-nutrient.conf"

# - pipeline.id: fetch-composition-pipeline
#   path.config: "/usr/share/logstash/pipeline/fetch-composition.conf"

# - pipeline.id: fetch-analysis-pipeline
#   path.config: "/usr/share/logstash/pipeline/fetch-analysis.conf"


