server:
  port: 8081

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cache:
    type: redis
  redis:
    # host: host.docker.internal # ??? ??
    # host: localhost # ???? ??
    host: "j6c104.p.ssafy.io"
    port: 6380