spring:
  datasource:
    url: jdbc:mysql://j6c104.p.ssafy.io:3306/dbmaster?characterEncoding=UTF-8
    username: dbmaster
    password: s06p22c104
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  logging.level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace